# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: MediaVC - NB master

trigger: none

schedules:
  - cron: "0 0 * * *"
    displayName: MediaVC daily NB master
    branches:
      include:
        - master
    always: false

pr:
  branches:
    exclude:
      - master
      - features/*
      - bugfixes/*
      - releases/*

pool:
  vmImage: windows-latest

steps:

    - task: UseDotNet@2
      displayName: Install .NET 5
      inputs:
        packageType: 'sdk'
        version: '5.0.x'

    - task: DotNetCoreCLI@2
      displayName: Restore solution
      inputs:
        command: 'restore'
        projects: '**/*.csproj'
        feedsToUse: 'select'
        configuration: NightlyBuild

    - task: DotNetCoreCLI@2
      displayName: Build solution
      inputs:
        command: 'build'
        projects: '**/*.csproj'
        configuration: NightlyBuild

    - task: VSTest@2
      displayName: Test solution
      inputs:
        testSelector: 'testAssemblies'
        testAssemblyVer2: |
          src/Tests/**\*test*.dll
          !**\*TestAdapter.dll
          !**\obj\**
        searchFolder: '$(System.DefaultWorkingDirectory)'
        runInParallel: true
        codeCoverageEnabled: true
        testRunTitle: 'MediaVC NB daily'
        configuration: 'NightlyBuild'
        rerunFailedTests: true
        rerunType: 'basedOnTestFailureCount'
        rerunFailedTestCasesMaxLimit: '3'
        rerunMaxAttempts: '2'

    - task: PublishTestResults@2
      displayName: Fail if tests are failed
      inputs:
        testResultsFormat: 'XUnit'
        testResultsFiles: 'D:\a\_temp\*.trx'
        failTaskOnFailedTests: true
        buildConfiguration: 'NightlyBuild'

    - task: DotNetCoreCLI@2
      displayName: Pack MediaVC.Core
      continueOnError: true
      inputs:
        command: 'pack'
        packagesToPack: 'src/MediaVC.Core/MediaVC.Core.csproj'
        configuration: 'NightlyBuild'
        versioningScheme: 'byPrereleaseNumber'
        majorVersion: '0'
        minorVersion: '9'
        patchVersion: '0'

    - task: DotNetCoreCLI@2
      displayName: Pack MediaVC
      continueOnError: true
      inputs:
        command: 'pack'
        packagesToPack: 'src/MediaVC/MediaVC.csproj'
        configuration: 'NightlyBuild'
        versioningScheme: 'byPrereleaseNumber'
        majorVersion: '0'
        minorVersion: '9'
        patchVersion: '0'

    - task: DotNetCoreCLI@2
      displayName: Pack MediaVC.Tools
      inputs:
        command: 'pack'
        packagesToPack: 'src/MediaVC.Tools/MediaVC.Tools.csproj'
        configuration: 'NightlyBuild'
        versioningScheme: 'byPrereleaseNumber'
        majorVersion: '0'
        minorVersion: '9'
        patchVersion: '0'

    - task: NuGetCommand@2
      displayName: Publish packages to Nuget.org
      inputs:
        command: 'push'
        packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
        nuGetFeedType: 'external'
        publishFeedCredentials: 'Nuget.org mateuszokroj1'