# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: MediaVC - nightly build

pr:
 branches:
   exclude:
     - master
     - features/*
     - bugfixes/*
     - releases/*

schedules:
  - cron: "0 0 * * *"
    displayName: MediaVC daily nightly build
    branches:
      include:
        - features/*
        - bugfixes/*
    always: false

pool:
  vmImage: windows-latest

steps:

    - task: UseDotNet@2
      displayName: Install .NET 5
      inputs:
        packageType: 'sdk'
        version: '5.0.x'

    - task: DotNetCoreCLI@2
      displayName: Restore solution
      inputs:
        command: 'restore'
        projects: '**/*.csproj'
        feedsToUse: 'select'
        configuration: Debug

    - task: DotNetCoreCLI@2
      displayName: Build solution
      inputs:
        command: 'build'
        projects: '**/*.csproj'
        configuration: Debug



    - task: DotNetCoreCLI@2
      
      displayName: Test solution
      inputs:
        command: 'test'
        projects: '**/*Tests.csproj'
        configuration: Debug
