# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: MediaVC - nightly build

variables:

  - template: templates/variables.yml

trigger: none

pr:
 branches:
   exclude:
     - master
     - features/*
     - bugfixes/*
     - releases/*

schedules:
  - cron: "0 0 * * *"
    displayName: MediaVC daily nightly build
    branches:
      include:
        - features/*
        - fixes/*
    always: false

pool:
  vmImage: ubuntu-latest

workspace:
  clean: all

steps:

  - template: templates/steps/sdk-installation.yml

  - template: templates/steps/restore&build-src.yml

  - template: templates/steps/test&fail.yml