# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: MediaVC - rolling build

variables:

  - template: templates/variables.yml

trigger:
- master
- features/*
- releases/*
- bugfixes/*

pool:
  vmImage: windows-latest

steps:

- task: UseDotNet@2
  displayName: Install .NET 6
  inputs:
    packageType: 'sdk'
    version: '6.0.x'

- task: DotNetCoreCLI@2
  displayName: Restore solution
  inputs:
    command: 'restore'
    projects: '$(SourceDirectory)/**/*.csproj'
    feedsToUse: 'select'
    configuration: Debug

- task: DotNetCoreCLI@2
  displayName: Build solution
  inputs:
    command: 'build'
    projects: '$(SourceDirectory)/**/*.csproj'
    configuration: Debug