# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: MediaVC - rolling build

trigger:
- master
- features/*
- releases/*
- bugfixes/*

pool:
  vmImage: windows-latest

steps:

- task: UseDotNet@2
  displayName: Install .NET 5
  inputs:
    packageType: 'sdk'
    version: '5.0.x'

- task: NuGetCommand@2
  displayName: Restore solution
  inputs:
    command: 'restore'
    restoreSolution: 'src/MediaVC.sln'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  displayName: Build solution
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    configuration: Debug