steps:

  - task: DotNetCoreCLI@2
    displayName: Test solution
    timeoutInMinutes: 10
    inputs:
      command: 'test'
      projects: '$(TestsDirectory)/**/*.Tests.csproj'

  - task: PublishTestResults@2
    displayName: Fail, if tests are failed
    timeoutInMinutes: 5
    inputs:
      testResultsFormat: 'XUnit'
      testResultsFiles: '$(Agent.TempDirectory)/**/*.trx'
      failTaskOnFailedTests: true
      buildConfiguration: 'Debug'