name: Rolling build

on:

  push:
    branches: [ main, feature/*, fix/*, release/* ]
    
  pull_request:
    branches-ignore: [ main, release/*, feature/*, fix/* ]
    
  workflow_dispatch:

jobs:

  build:

    name: RB Build on ${{ matrix.runsOn }}

    strategy:
      matrix:
        runsOn: ['ubuntu-latest', 'windows-latest', 'macOs-latest']

    runs-on: ${{ matrix.runsOn }}

    steps:
    
    - name: Cache
      uses: actions/cache@v3.0.2
      with:
        # A list of files, directories, and wildcard patterns to cache and restore
        path: src/*
        # An explicit key for restoring and saving the cache
        key: mediavc-rb
    
    - uses: actions/checkout@v3
      name: Git checkout
      
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore src
      
    - name: Build
      run: dotnet build src --no-restore
