name: Rolling build

on:

  push:
    branches: [ master, Architecture, feature/*, fix/*, release/* ]
    
  pull_request:
    branches-ignore: [ master, release/*, feature/*, fix/* ]
    
  workflow_run:

jobs:
  build:

    runs-on: windows-latest

    steps:
    
    - uses: actions/checkout@v3
      name: Git checkout
      
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
